### ISSUE TITLE
Incorrectly trying to migrate ESM entity names

### ISSUE THREAD

**Issue by henricm** [henricm/ha-ferroamp#48]
When handling ESM events, there seem to be some issue with the `migrate_entities` for ESMs which have id consisting only of numbers.

This error occurs when the ESM event is parsed:

```
 2021-07-24 11:08:06 ERROR (MainThread) [homeassistant.util.logging] Exception in esm_event_received when handling msg on 'extapi/data/esm': '{"status": {"val": "3"}, "soc": {"val": "17.700"}, "parentesoid": {"val": "20030049"}, "soh": {"val": "98.800"}, "ts": {"val": "2021-07-24T09:08:06UTC"}, "ratedCapacity": {"val": "10200.000"}, "id": {"val": "20030049"}}'
Traceback (most recent call last):
  File "/Users/henric/.homeassistant/custom_components/ferroamp/sensor.py", line 328, in esm_event_received
    migrate_entities(
  File "/Users/henric/.homeassistant/custom_components/ferroamp/sensor.py", line 508, in migrate_entities
    entity_registry.async_update_entity(
  File "/Users/henric/Projekt/home-assistant/homeassistant/helpers/entity_registry.py", line 390, in async_update_entity
    return self._async_update_entity(
  File "/Users/henric/Projekt/home-assistant/homeassistant/helpers/entity_registry.py", line 463, in _async_update_entity
    raise ValueError(
ValueError: Unique id 'ferroamp_esm_20030049-status' is already in use by 'sensor.ferroamp_esm_20030049_status'
```

I saw this when switched from a really old version. However, even then I remove the ESM entities, this error occurs so it probably appears on a fresh install too.

It seems like this regex is matching an entity id consisting of only numbers:
`REGEX_ESM_ID = re.compile(r"^(.+?)?-?(\d{8})\s*$")`
https://github.com/henricm/ha-ferroamp/blob/master/custom_components/ferroamp/const.py#L29

Not sure if that is intended or should it only match when id also contains other characters as described in #35?

Also, is it intentionally that we use `-status` instead of `_status` as suffix?

**Comment by argoyle** [comment]
Nice find! There's a PR for you to checkout. 😊
